### ISSUE TITLE
Declare all dependencies in mod manifest

### ISSUE THREAD

**Issue by LambdAurora** [kwpugh/veggie_way_fabric#11]
Please declare all dependencies required for the mod to launch in the mod manifest, nothing's more infuriating than a server that crashes randomly due to a missing dependency than directly at launch.

And no, CurseForge relations is not enough.

**Comment by kwpugh** [comment]
Hmm, so there is a way to do that.   I wasn't familiar with this.   Can you point me to an example of using a manifest.mf file?

**Comment by kwpugh** [comment]
so this is not done with a manifest file but within the fabric.mod.json.   I will add these as I update mods.   Thanks for pointing that out.

**Comment by LambdAurora** [comment]
> so this is not done with a manifest file but within the fabric.mod.json. I will add these as I update mods. Thanks for pointing that out.

The fabric.mod.json file is the *mod* manifest.
Manifest.mf file is a *JAR* manifest.

**Comment by kwpugh** [comment]
Do I need a jar manifest for anything.  Still learning Java.

**Comment by LambdAurora** [comment]
For a mod you don't need a Jar Manifest, else it can be used to specify the main class of a Java executable usually.

**Comment by kwpugh** [comment]
ok, thanks for the pointer.
