### ISSUE TITLE
[1.17.1[ Soy Milk to substitute cow's milk

### ISSUE THREAD

**Issue by 0xmycf** [kwpugh/veggie_way_fabric#12]
Hey there,
very interesting mod, you can almost live vegan, except for the milk.
Have you ever considered adding Soy Milk? 

Thank you for your great work.

Another question:
What exactly is com.kwpugh:pugh_lib_fabric_1.17.1:1.1.5 ? I tried to fork the mod and add it myself (to use it privately) but my IDE couldn't find it and neither did I really.

~mycf / DruDo

**Comment by kwpugh** [comment]
I have been thinking about Soy Milk.

PughLib is a private library in my local Maven that handles the recipe remainder for some of the tools (i.e. tools stay in crafting grid and take durability).  I do not plan to make that public to avoid mod conflicts.

**Comment by kwpugh** [comment]
prerequisites: grow soybeans and make tofu

So, 1st we make a bucket of Raw Soy Milk
![Screen Shot 2021-07-21 at 8 41 15 PM](https://user-images.githubusercontent.com/8809210/126579859-4c1b6958-740f-4fa5-92a4-e952916f04ac.png)

2nd, we heat it up on a campfire
![Screen Shot 2021-07-21 at 8 41 34 PM](https://user-images.githubusercontent.com/8809210/126579911-7599a480-9559-45d9-833e-24ad5c8aa3c9.png)

3rd, we craft stuff with it
![Screen Shot 2021-07-21 at 8 41 49 PM](https://user-images.githubusercontent.com/8809210/126579926-c6cda13d-b76e-4dd7-98c8-f71e74a860ef.png)

The cooked Soy milk bucket will have 16 uses
![Screen Shot 2021-07-21 at 8 43 27 PM](https://user-images.githubusercontent.com/8809210/126579978-4851e5d3-8f4c-4e0f-b6ee-3b985ccfc2fc.png)

What do you think?

**Comment by kwpugh** [comment]
Hmm, the tags seem to work with Croptopia, nice

![Screen Shot 2021-07-21 at 9 10 51 PM](https://user-images.githubusercontent.com/8809210/126581663-0ef2aeee-edc3-46d3-97a6-360221d3edcb.png)

**Comment by kwpugh** [comment]
Add to v1.1.17, enjoy.

**Comment by 0xmycf** [comment]
Thank you very much! Nice work!
