### ISSUE TITLE
[1.18.2] Why are there dup seeds recipes?

### ISSUE THREAD

**Issue by Laifsyn** [kwpugh/veggie_way_fabric#13]
![image](https://user-images.githubusercontent.com/99366187/160063696-b92ce82a-953a-4650-a96a-8900c989d2e0.png)

**Comment by kwpugh** [comment]
it prevents two empty milk buckets from being crafted into a full bucket.

Is this causing a problem?

**Comment by Laifsyn** [comment]
is that the bug? because I used a datapack to invalidate the recipe because I wanted to keep minimal the amount of recipes that could be shown by REI

**Comment by Laifsyn** [comment]
![image](https://user-images.githubusercontent.com/99366187/160221942-8a5ae433-2f20-4307-8ea8-4609415f21ba.png)
well, apparently the bug doesn't exist? I'm on 1.18.1 though

**Comment by kwpugh** [comment]
sorry, two soy milk buckets, not vanilla

**Comment by Laifsyn** [comment]
two cooked soy milk results me into a cooked soymilk. raw soymilk doesn't. Is it only that ?

**Comment by kwpugh** [comment]
ok, I will take a look in 1.18.2.   So the extra recipe doesn't cause any problems though?

**Comment by Laifsyn** [comment]
no, it isn't a real problem. At least for me. I was just further inquiring just in case there was another bug so I re-validated the dup_seed recipes

**Comment by kwpugh** [comment]
ok.  I have sooo many mods it is sometimes hard to remember why I did something, Lol.

**Comment by Laifsyn** [comment]
at the very least, 2 cooked soymilk to 1 cooked soymilk is better than into 1 soy seed. So if there's no more bugs, I would keep my datapacks as they are

**Comment by kwpugh** [comment]
I'll take a look.

I'm working on another mod right now.

**Comment by kwpugh** [comment]
I'm going to keep the default to yield seeds, since it is the least of bad choices to avoid dupping.
