### ISSUE TITLE
[1.18.2] [SUGGESTION] Add dehydration support

### ISSUE THREAD

**Issue by Sunconure11** [kwpugh/veggie_way_fabric#14]
Just what it says on the tin. Can be done via tags.

**Comment by kwpugh** [comment]
Looks like the mod already provides tags for players to create a datapack for fluid support.

**Comment by Sunconure11** [comment]
I was referring more to the items and such

**Comment by Sunconure11** [comment]
https://github.com/Globox1997/Dehydration/tree/1.18/src/main/resources/data/dehydration/tags/items

**Comment by kwpugh** [comment]
you can add any items to the Dehydration mod you want via a datapack.

If I add them to the my mod and Dehydration is not present, it will cause errors.

The point of the tags is to make things mod independent

Welcome to the new world of data-driven modding!

**Comment by Sunconure11** [comment]
Hm, I'm noticing a thing. You don't need to use tags to have support. After talking with a specific dev, I think you might just need to define specific things in your drink item's class. Let me look a little further as to find how this is done.

**Comment by Sunconure11** [comment]
Try defining the actions for your drinks as well, drinking.

>     public UseAction getUseAction(ItemStack stack) {
>         return UseAction.DRINK;
>     }

Try adding this to said classes and see if it works. Dehydration has it's own sound for drinks, so it should give you a sound cue if it is working.

**Comment by kwpugh** [comment]
Many of my foods do not use individual classes, because they are not needed.  I just extend Item and attach food attributes to them.  

For drinks, I just use a DrinkBase class for all drinks and it has the UseAction.

I have getUseAction() defined in my DrinkBase class and I then just extend DrinkBase on any class that needs it, reducing dup code.

**Comment by kwpugh** [comment]
I think this is best handled by data packs that wish to support it.
