### ISSUE TITLE
[20w18a-1.0.1] Saturation, light and smoker issues

### ISSUE THREAD

**Issue by Omni35** [kwpugh/veggie_way_fabric#2]
A few issues I found with the 1.16 snapshot version.

The saturation doesn't seem right, changing the value in config doesn't seem to affect it.
All foods beside soups seem to give 10 saturation (soups 6), and with AppleSkin added they show huge values between 14 to even 54 for saturation.
The new plants give off light when planted, don't know if that's indended.
Fresh Tofu and Dough can't be cooked in a smoker.

**Mod Version:** TheVeggieWay_Fabric_20w18a-1.0.1
**Fabric Version:** fabric-loader-0.8.2+build.194-20w18a
**Fabric API version:** fabric-api-0.10.3+build.338-1.16

![2020-05-05_18 46 56](https://user-images.githubusercontent.com/7506611/81096731-26fed780-8f07-11ea-90f6-f6216610e12c.png)
![2020-05-05_19 33 03](https://user-images.githubusercontent.com/7506611/81096837-48f85a00-8f07-11ea-93f6-7eace0402d1d.png)

**Comment by kwpugh** [comment]
fixed in next update
