### ISSUE TITLE
[Request] Make Raw Veggie Items Edible; Add Cooked Versions

### ISSUE THREAD

**Issue by PickleWeaselPhD** [kwpugh/veggie_way_fabric#3]
The extra food items the mod provides are great, but I would like to request that the raw produce be edible as well. Not being able to eat the raw items, or even having a cooked equivalent item feels odd. Perhaps they could provide the same hunger and saturation as potatoes and baked potatoes?

**Comment by kwpugh** [comment]
Next version will add values for the Raw Foods (corn, quinoa, lentil, and soybean)
Also, Cooked Tofu now has food values.

And, the hunger and saturation of the above can be adjusted in the config.
