### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by DanShu15** [kwpugh/veggie_way_fabric#4]
Would it be possible to disable VeggieWay corn/seeds when TacoCraft is installed, and use the corn from TacoCraft for VeggieWay recipes?
Also wondering if Mill recipes can be made compatible with Tech Reborn grinders and Simple Quern?

Also a feature request - is it possible to get these seeds specifically from grass rather than dirt? We're filling up our inventories down in our mines lol

**Comment by kwpugh** [comment]
Thank you for the feedback.

In general, I would only be making these changes in 1.16, I'm not planning on adding anymore features to the 1.15.2 version.

That said, let me break these down:
- Using corn from TacoCraft is up to that mod adjusting the recipes to accept common tagged corn.   I have already created tags for "corn" and my recipes use them.
- Mill recipe integration into tech mods like TechReborn are beyond the scope of this mod, as the Mill is intended to be a very simple item, not a machine.
- Next release of 1.16 will disable seeds dropping from dirt, and only drop from grass.

Regards.

**Comment by kwpugh** [comment]
I pushed v1.0.6 for 1.15.2 that disables seed drops from Dirt and Grass blocks.

**Comment by DanShu15** [comment]
Very kind of you :) I'm pumped that 1.16 is so close, I totally understand. I've built a modpack and fixed all but 1 major bug before I was going to release it, but with 1.16 knocking there's no point in a 1.15.2 version going to the public :)

I'll let Tacocraft know about the corn tag. I think I can add a recipe for the dough myself, so that's nbd. It'd just be neat to come prepackaged ready to rock with those couple others if they're installed so it was worth a request :)
