### ISSUE TITLE
Right-Click Harvest

### ISSUE THREAD

**Issue by nephatrine** [kwpugh/veggie_way_fabric#7]
Would love to be able to use the [SimpleHarvest](https://www.curseforge.com/minecraft/mc-mods/simpleharvest) mod to harvest the crops this mod adds, but even when added to its configuration it does not work. Would you consider adding an option to right-click harvest into your mod? It's cumbersome when all my other crops work the same way except for this mod's.

**Comment by kwpugh** [comment]
Can you share an example of a crop mod that DOES work so I can see what they are doing?   My crops seem to work fine if you add them to the harvest.json config file though.

**Comment by kwpugh** [comment]
You have to add the Veggieway crops to the SimpleHarvest config and they work fine.   I do not want to implement a separate features for right-clicking crops.
