### ISSUE TITLE
1 Bucket of water for a pie/piece of Tofu

### ISSUE THREAD

**Issue by heyjudek** [kwpugh/veggie_way_fabric#9]
Unfortunately many recipes this mod adds are very unpractical to use because of this requirement. I think it would be a lot better if 1 bucket of water made 16 or more pies instead of just one. 1 ton of water for a single pie just seems too much.

**Comment by kwpugh** [comment]
This is a difference of opinion regarding the recipe.   If you wish to change it, you can use a datapack or CraftTweaker.
